### ISSUE TITLE
Break when post has no Taxonomy

### ISSUE THREAD

**Issue by tian2992** [afinidata2019/afinidata-content-manager#17]
``` GET /posts/283/edit/
Internal Server Error: /posts/283/edit/
Traceback (most recent call last):
  File "/home/ubuntu/content_manager_venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/content_manager_venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/content_manager_venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/content_manager_venv/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/content_manager_venv/lib/python3.5/site-packages/django/contrib/auth/mixins.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/ubuntu/content_manager_venv/lib/python3.5/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/content_manager_venv/lib/python3.5/site-packages/django/views/generic/edit.py", line 190, in get
    return super().get(request, *args, **kwargs)
  File "/home/ubuntu/content_manager_venv/lib/python3.5/site-packages/django/views/generic/edit.py", line 133, in get
    return self.render_to_response(self.get_context_data())
  File "/home/ubuntu/content_manager/posts/views.py", line 328, in get_context_data
    if post.taxonomy:
  File "/home/ubuntu/content_manager_venv/lib/python3.5/site-packages/django/db/models/fields/related_descriptors.py", line 415, in __get__
    self.related.get_accessor_name()
posts.models.Post.taxonomy.RelatedObjectDoesNotExist: Post has no taxonomy.
GET /posts/283/edit/ - 500
```

**Comment by tian2992** [comment]
Fixed on last merge
